### ISSUE TITLE
Wrong MOS score

### ISSUE THREAD

**Issue by gledim** [sipcapture/homer-app#410] opened 2021-02-11 23:13 UTC
Hi guys,

In the QOS reports, we are noticing some calls getting MOS scores of 1 either from the beginning, or starting at some point, and continuing till the end of the call.

After some investigations, we noticed that at the point where MOS goes to 1, there are some lost packets.

From some old issues raised in Homer-Api, we found out that the MOS is calculated from a function that takes these missed packets in consideration, among others. Fixes for these issues seem to have been pushed at the respective repositories at the time, but is there any change they haven't been migrated to the new version?

We also couldn't find any reference of these calculating functions in the homer-app repo. Can you please point them out?

Glad to help with anything :)

**Comment by lmangani** [comment] 2021-02-11 23:32
Hi @gledim We know exactly what you're talking about here - and this is more about about how RTCP itself works and how this applies to the MOS estimation - unlike our RTPAgent reports and as you know RTCP packet loss is reported as an incremental counter without "resets" in between the chain of reports and as such it gets displayed. We can of course adjust things to get more flexible but at the same time, we need to keep the tool honest towards the protocol it reports for as well. Our RTP analyzer does this the way you would expect.

Could you please attach a sample RTCP dataset affected so we can discuss with some visible numbers and confirm?

**Comment by gledim** [comment] 2021-02-15 22:43
Thank you @lmangani 

Yes, I was thinking exactly about this while investigating it.

I am attaching a sample dataset, that has some lost packets reporte, please let me know what do you think
[rtcp_set.zip](https://github.com/sipcapture/homer-app/files/5984435/rtcp_set.zip)

**Comment by jacovinus** [comment] 2021-02-18 10:46
Good morning @gledim, we've analyzed your CSV file, but don't see any packets or MOS related data. Is the file corrupted perhaps? Please help us providing the complete file so we can help you :) .

**Comment by gledim** [comment] 2021-02-20 01:11
Hi @jacovinus 
That is an extract of the DB records for the call, probably not very helpful :)
I'm attaching the trace for another call, as captured locally and as exported from Homer
Please let me know if anything else is needed
[traces.zip](https://github.com/sipcapture/homer-app/files/6013861/traces.zip)

**Comment by rogelio-telnyx** [comment] 2021-02-22 20:24
@lmangani thanks for clarifying what's causing this issue. Can you please tell us how we can modify the MOS score calculation to consider incremental packet loss instead? Thanks!

**Comment by lmangani** [comment] 2021-02-23 08:47
Hi @rogelio-telnyx The only way around it would be subtracting the preceding loss value from each RTCP round before the MOS calculation is performed. Will discuss it with the team.

**Comment by rogelio-telnyx** [comment] 2021-03-08 19:35
@lmangani thanks for the confirmation, is there anything we can do here to help speed up the implementation of this fix?

**Comment by rogelio-telnyx** [comment] 2021-03-24 05:08
@lmangani according to [rfc3550](https://tools.ietf.org/html/rfc3550) RTCP messages contain two values related to packet loss: "cumulative number of packets lost" and "fraction lost". 
The "fraction lost" metric seems to use the same approach as the packet loss metric from RTPAgent:
```fraction lost: 8 bits The fraction of RTP data packets from source SSRC_n lost since the previous SR or RR packet was sent, expressed as a fixed point number with the binary point at the left edge of the field. (That is equivalent to taking the integer part after multiplying the loss fraction by 256.) This fraction is defined to be the number of packets lost divided by the number of packets expected, as defined in the next paragraph. An implementation is shown in Appendix A.3. If the loss is negative due to duplicates, the fraction lost is set to zero. Note that a receiver cannot tell whether any packets were lost after the last one received, and that there will be no reception report block issued for a source if all packets from that source sent during the last reporting interval have been lost.```

I confirmed that "fraction lost" is already stored in the Homer data set, so the question is, can we tell Homer to use this value instead of "cumulative number of packets lost" for MOS calculation?

**Comment by gledim** [comment] 2021-04-27 21:13
Hey @lmangani @jacovinus 
By investigating some sample traces, we have noticed that there is an error in calculating the packets_lost , but this seems to be an issue happening in the HEP server.

So, whenever the cumulative number of lost packets is increase by 1 in RTCP packets, in Homer it is increased by 256. This then affects the MOS calculation, and whenever this happens, MOS drops to straight 1

Attached I'm putting 2 RTCP packets where this happens, and the respective one extracted from a trace from homer-app.

[traces1.zip](https://github.com/sipcapture/homer-app/files/6387679/traces1.zip)

In case more details are needed, please let me know

**Comment by adubovikov** [comment] 2021-04-27 22:23
Hi,

I am not sure that you look at the correct field. In the latest version we
take fraction packet loss and not cumulative loss. And this number should
be multiplied by 256 because the field is usigned 8 bits integer. (RFC
rtcp)

Regards,
Alexandr

**Comment by adubovikov** [comment] 2021-04-28 07:21
Hi,

ok I see... who has generated that HEP message ?


Regards,
Alexandr

**Comment by adubovikov** [comment] 2021-04-28 10:57
ok, all good!

LostPercentage=100.0*(float)report_block_get_fraction_lost(rb)/256;

Let me do the change!

**Comment by adubovikov** [comment] 2021-04-28 11:17
so, anyway please tell us who generated that HEP

**Comment by rogelio-telnyx** [comment] 2021-04-28 16:36
@adubovikov we created a custom FreeSWITCH module that converts all RTCP messages that FS sends or receives into HEP messages that are sent to heplify server.
We're putting together an example from a call that shows the values at the 3 stages: 
- RTCP Message sent/received by FS 
- HEP Message sent by FS
- RTCP message shown by Homer App

This will help us understand where's the problem, please hold while we prepare the data.

**Comment by adubovikov** [comment] 2021-04-28 19:26
@rogelio-telnyx sure, but this is already almost clear that looks like you send fraction_loss as packet_loss and cumulative as fraction. Please check these values!

**Comment by rogelio-telnyx** [comment] 2021-04-28 20:33
@adubovikov indeed that's what we found! We will make the necessary modifications to the custom FS module and report back once we fully test it. Thanks

**Comment by adubovikov** [comment] 2021-04-28 20:51
@rogelio-telnyx :-) good luck!

**Comment by adubovikov** [comment] 2021-05-11 11:28
https://github.com/sipcapture/homer-ui/commit/0d3b297e66c8948bed46e15e0173ccac818903ca

fixed

**Comment by lmangani** [comment] 2021-05-13 12:36
@piotrgregor could you confirm if the patch was successful from your side of the integration?

**Comment by lmangani** [comment] 2021-05-16 09:51
Closing as resolved. Feel free to reopen if needed ;)

**Closed by lmangani** 2021-05-16 09:51 UTC
Labels: help wanted, question

**Comment by piotrgregor** [comment] 2021-05-17 09:41
Yes. Thanks @lmangani
