### ISSUE TITLE
homer-app dont show : between hostname and port

### ISSUE THREAD

**Issue by khorsmann** [sipcapture/homer-app#350] opened 2020-05-18 14:42 UTC
Hi there,

using homer-docker images with homer7-7 branch and 
sipcapture/webapp   latest              fe3a3a1d20af image. After upgrading to this, i saw, that the spliting element (i thought it was an : sign) is missing.

See this picture:
![image](https://user-images.githubusercontent.com/5255309/82226124-65908b00-9926-11ea-9433-c4272eb3ecbf.png)

**Comment by systemcrash** [comment] 2020-05-19 12:07
Fixed already in today's build. This was caused by 
sipcapture/homer-ui/pull/227
and was fixed by
sipcapture/homer-ui/pull/230

run `docker-compose pull homer-webapp`

This issue can be closed, I think.

**Closed** 2020-07-08 09:08 UTC
Labels: bug
