### ISSUE TITLE
No QOS data in Docker version of H7.7

### ISSUE THREAD

**Issue by cerienj** [sipcapture/homer-app#300] opened 2020-02-18 18:49 UTC
H7.7 has been installed smoothly via the docker compose. See version at the end.

While call data is fine, and RTCP data appears in the log, the QOS tab for any call is empty . No graph, (the axis are drawn, no data), and clicking on labels just show 0 values for all labels

This is on a VM and not in production, so I am available for reinstall / testing.

Great work on H7.7. !!!
J.

Ex: of logs data:
```
payload:
message: Object {"sender_information":{"ntp_timestamp_sec":3791028439,"ntp_timestamp_usec":687220770,"rtp_timestamp":80563856,"packets":500,"octets":10000},"ssrc":1559790771,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":489063601,"fraction_lost":0,"packets_lost":0,"highest_seq_no":26939,"ia_jitter":4,"lsr":2161263736,"dlsr":317259}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_Duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":1559790771}
timestamp: Tue Feb 18 2020 11:27:19 GMT-0400 (Atlantic Standard Time)
raw: Object {"captureId":"245","capturePass":"myhep","correlation_id":"5577906a1659a0ff4989357b3cb8eae9@sip.xxxxxx","create_date":1582039639160,"dbnode":"local","dstIp":"zzzzzzz","dstPort":10019,"id":137,"node":["245","local"],"payloadType":5,"profile":"5_default","proto":"rtcp","protocol":17,"protocolFamily":2,"sid":"5577906a1659a0ff4989357b3cb8eae9@sip.xxxxxx","srcIp":"tttt","srcPort":19055,"timeSeconds":1582039639,"timeUseconds":160025}
```

os: debian 9.12
Docker version 19.03.6
docker-compose version 1.25.4

Homer 7.7.0.28(prod)
heplify-server 1.15
homer-app: VERSION: 1.1.3

On the capture node: heplify 1.0

**Comment by adubovikov** [comment] 2020-02-18 20:09
are you sure about homer-app version 1.1.3 ? maybe 1.1.30 ?

**Comment by cerienj** [comment] 2020-02-18 20:14
Sorry ! wrong cut & paste: 
VERSION: 1.1.31

**Comment by negbie** [comment] 2020-02-18 20:19
Just tested the same and can confirm. In console I see error {data: "", message: "no advacned settings found for type cdr"}

**Comment by adubovikov** [comment] 2020-02-18 20:20
> Just tested the same and can confirm. In console I see error {data: "", message: "no advacned settings found for type cdr"}

CDR ? ok. @RFbkak37y3kIY Do you have something to say ?

**Comment by adubovikov** [comment] 2020-02-18 20:21
@cerienj @negbie how do you feed the RTCP packets ? rtpengine/asterisk ?

**Comment by negbie** [comment] 2020-02-18 20:21
clone heplify repo and do ./heplify -rf example/pcap/rtp_rtcp_sip_ipv4_udp.pcap -e

**Comment by adubovikov** [comment] 2020-02-18 20:22
ok, normaly we do tests with hepgen, let me use heplify in this case

**Comment by negbie** [comment] 2020-02-18 20:31
Im just playing with it and not using it really so everything I do are synthetic tests with heplify -rf some file

**Comment by negbie** [comment] 2020-02-18 20:32
But I would assume thats it's broken for rtpengine or asterisk to because format should be the same?

**Comment by cerienj** [comment] 2020-02-18 20:36
> @cerienj @negbie how do you feed the RTCP packets ? rtpengine/asterisk ?

different asterisk boxes, running heplify, version 1.55 now - 


`heplify155 -i eth0 -myhost:9060 -hi 5959 -e -m SIPRTCP`

**Comment by cerienj** [comment] 2020-02-18 20:46
I see two sessions loaded into homer, 12013223@200.57.7.195 and 12015624@200.57.7.195
12013223@200.57.7.195 show a QOS tab, empty, 
12015624@200.57.7.195 does not show a QOS tab (which makes sense, there is an invite but no 200 OK).

Here is the heplify result:
```
./heplify155  -rf rtp_rtcp_sip_ipv4_udp.pcap -e
2020/02/18 20:42:16.405669 sniffer.go:114: INFO config.Config{Iface:(*config.InterfacesConfig)(0xc000150c00), Logging:(*logp.Logging)(0xc0000a80f0), Mode:"SIPRTCP", Dedup:false, Filter:"", Discard:"", DiscardMethod:"", Zip:false, HepServer:"127.0.0.1:9060", HepNodePW:"", HepNodeID:0x7d2, HepNodeName:"", Network:"udp", Protobuf:false, Reassembly:false}
2020/02/18 20:42:16.405814 sniffer.go:115: INFO &config.InterfacesConfig{Device:"any", Type:"pcap", ReadFile:"rtp_rtcp_sip_ipv4_udp.pcap", WriteFile:"", RotationTime:60, PortRange:"5060-5090", WithVlan:false, WithErspan:false, Snaplen:8192, BufferSizeMb:32, ReadSpeed:false, OneAtATime:false, Loop:1}
2020/02/18 20:42:16.405867 sniffer.go:116: INFO bpf: (tcp or sctp) and greater 42 and portrange 5060-5090 or (udp and greater 128 and portrange 5060-5090 or ip[6:2] & 0x1fff != 0 or ip6[6]=44) or (ip and ip[6] & 0x2 = 0 and ip[6:2] & 0x1fff = 0 and udp and udp[8] & 0xc0 = 0x80 and udp[9] >= 0xc8 && udp[9] <= 0xcc)
2020/02/18 20:42:16.405917 sniffer.go:123: INFO ostype: linux, osarch: amd64
2020/02/18 20:42:16.406889 sniffer.go:363: INFO Read in pcap file. Stats won't be generated.
```

**Comment by negbie** [comment] 2020-02-18 20:48
@adubovikov keep in mind that this is a response from agentsub

return reply.String(), fmt.Errorf("no advacned settings found for type %s", typeRequest)

easy to spot because of the typo in advanced ;)

**Comment by negbie** [comment] 2020-02-18 20:49
So I think this console error is unrelated to empty QOS tab.

**Comment by cerienj** [comment] 2020-02-18 20:51
where would I find this in the docer install ? which components issues it ?

**Comment by adubovikov** [comment] 2020-02-18 21:01
so, confirmed. Created a ticket for dev-UI :-) ...

**Comment by adubovikov** [comment] 2020-02-18 21:08
> @adubovikov keep in mind that this is a response from agentsub
> 
> return reply.String(), fmt.Errorf("no advacned settings found for type %s", typeRequest)
> 
> easy to spot because of the typo in advanced ;)

Yes, thank you fixed all 6 :-)

**Comment by adubovikov** [comment] 2020-02-18 21:11
@cerienj but you have the RTCP packets in the Message view ?

**Comment by cerienj** [comment] 2020-02-18 21:21
Yes, I see them in the message & flow view. Also, I see data (from my hosts) in the Grafana / QoS dashboard

**Comment by adubovikov** [comment] 2020-02-18 21:22
ok, great. Tomorrow it will be fixed. Just wait a while.

**Comment by cerienj** [comment] 2020-02-18 21:27
awesome !

**Comment by DarrenCarterSA** [comment] 2020-02-19 05:38
Thank you! I spent the better part of yesterday trying to figure this out. No QoS stats.
Sending from RTPEngine.

**Comment by adubovikov** [comment] 2020-02-19 10:34
![Screenshot from 2020-02-19 11-29-08](https://user-images.githubusercontent.com/4513061/74826287-9d7a3900-530b-11ea-9cb6-486d6416699f.png)

so, fixed in the dev branch, we will fix couple another issues and implement couple new features and after test will release a new package

**Comment by cerienj** [comment] 2020-02-19 13:21
That looks great !!!! quite eager to see it myself :-)

**Comment by adubovikov** [comment] 2020-02-19 23:57
https://github.com/sipcapture/homer-app/releases/tag/1.1.32
also the packages are in the repository. Please update

**Comment by summitrabz** [comment] 2020-02-20 02:34
Is this update applies to the docker version only? Would be nice if the update is also available on non-docker version :)

**Comment by adubovikov** [comment] 2020-02-20 07:19
This is for all

**Comment by adubovikov** [comment] 2020-02-20 15:39
sorry, we have updated the docker version  as well!

**Comment by adubovikov** [comment] 2020-02-20 22:31
any updates here ?

**Comment by adubovikov** [comment] 2020-02-20 22:32
@cerienj please close the ticket if all good

**Comment by summitrabz** [comment] 2020-02-20 23:40
Thanks, Alex for the update. I'm using the non-docker version, with Homer-App version 1.1.32 and also using heplify 1.55 to send packets with the following command

./heplify -hs 192.168.120.167:9060 -e

The QoS report is empty with no data


![image](https://user-images.githubusercontent.com/47308455/74989938-eeb63400-5495-11ea-9c59-36ceeac41e3c.png)

![image](https://user-images.githubusercontent.com/47308455/74990094-671cf500-5496-11ea-890f-6e787fd044b6.png)

**Comment by adubovikov** [comment] 2020-02-21 09:30
@summitrabz did you install it as a package ? Are you sure that your UI is >= 7.7.028 ?

**Comment by cerienj** [comment] 2020-02-21 14:26
sorry - I was unavailable yesterday - I'm looking at branch 7.7 of sipcatpure/docker and Latest commit
8f8d14c - 4 days ago - I dont see your changes (on master, last commit is last month)

(https://github.com/sipcapture/homer7-docker/tree/7.7)

**Comment by lmangani** [comment] 2020-02-21 14:29
@cerienj the changes are in the docker container, not on the docker compose.
What you need to be doing: 
```
docker pull sipcapture/webapp
````
or
```
docker-compose pull
```

**Comment by cerienj** [comment] 2020-02-21 14:40
still nothing, with either the test data or my data

**Comment by lmangani** [comment] 2020-02-21 14:47
Test your setup with hepgen - replace the IPs and commands if needed:
```
cd /usr/src
git clone https://github.com/sipcapture/hepgen.js
cd hepgen.js
npm install
nodejs hepgen.js -s HOMER.IP.GOES.HERE -p 9060 -c ./config/b2bcall_rtcp.js
```

**Comment by adubovikov** [comment] 2020-02-21 14:51
@cerienj can you provide your data by dumping sip and rtcp table ? You can send it private if you prefer.

**Comment by cerienj** [comment] 2020-02-21 14:56
ok, with hepgen, I do get data in the qos window

**Comment by lmangani** [comment] 2020-02-21 14:58
@cerienj then your setup is doing just fine and you need to look into what's being sent and how

**Comment by adubovikov** [comment] 2020-02-21 15:07
@cerienj if you can, please send me your RTCP data only in the dump format. We will play back on our server

**Comment by adubovikov** [comment] 2020-02-21 15:08
@cerienj SQL dump

**Comment by cerienj** [comment] 2020-02-21 15:11
I am using heplify 155 to capture data, with the following syntax: 
`heplify -i eth0 -hs myhomer:9060 -hi 1234 -e -m SIPRTCP

**Comment by cerienj** [comment] 2020-02-21 15:13
which table do you want exactly ?

**Comment by adubovikov** [comment] 2020-02-21 15:19
hep_proto_5_default

**Comment by cerienj** [comment] 2020-02-21 15:33
data is here: https://drive.google.com/open?id=1-Y4MWGTm6h8Anh3pZ6SESbmGta_5-c4I

**Comment by cerienj** [comment] 2020-02-21 15:33
I've extracted 10,000 records

**Comment by adubovikov** [comment] 2020-02-21 16:34
thanks, are you sure your time is correct ? 
in the data I see: '2020-02-21 11:28:31.534'
but inside timestamp 1582298911 that should be "02/21/2020 @ 3:28pm (UTC)"  4 hours diff ? Or the server is in -4 GMT ?


```

**Comment by cerienj** [comment] 2020-02-21 16:45
Capture node is gmt+1, Homer gmt-4, I have the same issue with a server on
the same time band as Homer

**Comment by adubovikov** [comment] 2020-02-21 16:48
just upload your data and corrected the time.

![Screenshot from 2020-02-21 17-46-34](https://user-images.githubusercontent.com/4513061/75053837-3a86ce80-54d2-11ea-95be-aa1aca8095a9.png)

the original call id was: "5e4687ef2d1bb6220090247b6c2a64ff@sip59.ipertelecom.fr"

Can you check on your side ?

**Comment by adubovikov** [comment] 2020-02-21 20:18
Just uploaded a new release 1.1.35 UI 7.7.030 please install

**Comment by cerienj** [comment] 2020-02-21 21:46
it works with my existing data !!!!! That is AWESOME !!!!

**Comment by adubovikov** [comment] 2020-02-21 21:47
great :-) give a star, close the ticket!  
Have a nice week end :-)

**Closed** 2020-02-21 21:53 UTC

**Comment by adubovikov** [comment] 2020-02-21 22:07
@cerienj probably need to delete hep_proto.gz and screenshots with your hostsnames, just to avoid some curious people :-)
