### ISSUE TITLE
"search" function issue related to range filters

### ISSUE THREAD

**Issue by Demon-DK** [sipcapture/homer-app#155] opened 2019-06-18 22:29 UTC
I'm using default deploy of following stack in the docker images:
```
    image: sipcapture/heplify:master
    image: sipcapture/heplify-server:master
    image: sipcapture/homer-app:master
    image: postgres:10-alpine
```

The issue is simple to reproduce
1) Make call (_e.g. for the case below at 1:13:43_)
2) Go to the web interface and try to find latest
3) If you have time range filter is set as **"last hour"** you will not find it
![Screenshot_1](https://user-images.githubusercontent.com/25489257/59724079-59d9a780-9231-11e9-9633-97ab352067d3.jpg)

4) If you change time range filter to **"last 10 min"** or **"last 30 min"** - success !
![Screenshot_3](https://user-images.githubusercontent.com/25489257/59724140-82fa3800-9231-11e9-9ceb-7fafc7ac4643.jpg)

5) If you try to get back to **"last hour"** its again will not work

**Comment by aqsyonas** [comment] 2019-06-21 17:45
@Demon-DK i was unable to reproduce it, could you try it on the latest build.

**Comment by Demon-DK** [comment] 2019-06-23 20:58
>  i was unable to reproduce it, could you try it on the latest build.

Yeap, but actually I am already using the latest as you can see.
```image: sipcapture/homer-app:master```

At their docker hub there are no tag **latest** only **master** tag is the latest one.

**Comment by lmangani** [comment] 2019-11-28 19:07
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!

**Closed by lmangani** 2019-11-28 19:07 UTC
