### ISSUE TITLE
QoS tabsence for all call flows (with media) - how to associate RTCP with calls?

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#342] opened 2020-05-12 14:38 UTC
Pulled in 'yesterdays' build of webapp. Reviewing any call flow produces the web browser console error:

`error 
Object { data: "", message: "no agent subscription object found for type [cdr]" }`

More specifically:

```
ngOnInit http://thishost/main.5be002036effe68df150.js:1
    invoke http://thishost/polyfills.635d703039731e52383d.js:1
    onInvoke http://thishost/main.5be002036effe68df150.js:1
    invoke http://thishost/polyfills.635d703039731e52383d.js:1
    run http://thishost/polyfills.635d703039731e52383d.js:1
    O http://thishost/polyfills.635d703039731e52383d.js:1
    invokeTask http://thishost/polyfills.635d703039731e52383d.js:1
    onInvokeTask http://thishost/main.5be002036effe68df150.js:1
    invokeTask http://thishost/polyfills.635d703039731e52383d.js:1
    runTask http://thishost/polyfills.635d703039731e52383d.js:1
    y http://thishost/polyfills.635d703039731e52383d.js:1
    invokeTask http://thishost/polyfills.635d703039731e52383d.js:1
    f http://thishost/polyfills.635d703039731e52383d.js:1
    p http://thishost/polyfills.635d703039731e52383d.js:1
```

But if I look in settings -> Agentsub, sure enough, there is a GUID row, albeit which has expired. 

I can click the red garbage icon, but I'm concerned that I will not be able to undo anything. There is no indication I can regain an `Agentsub` - whatever that is. Does this happen automatically at some connect or startup?

**Comment by adubovikov** [comment] 2020-05-12 14:40
this is HEPSUB external subscription. If you don't have it - ignore it :)

**Comment by systemcrash** [comment] 2020-05-12 14:41
Ah, because clicking delete shows, BIG FAT RED WARNING:
```
Are you sure?

Your will not be able to recover this!
```

**Comment by systemcrash** [comment] 2020-05-12 14:43
So... what (verifiable) "settings" are necessary so I get a QoS tab on call flows?

**Comment by lmangani** [comment] 2020-05-12 15:11
Disappeared? Is this confirmed from calls with known statistics and/or are there any client side errors while opening those sessions?

**Comment by systemcrash** [comment] 2020-05-13 10:56
Looking in Grafana, I see the Jitter graph fill nicely - but I open that call in the graph in Homer. No tab. What client side (web browser?) errors should I look out for, aside from the ones I mentioned at the start?

**Comment by adubovikov** [comment] 2020-05-13 10:58
do you have rtcp messages in your PG DB ?

**Comment by systemcrash** [comment] 2020-05-13 11:00
How does one confirm this?

**Comment by adubovikov** [comment] 2020-05-13 11:18
select * from hep_proto_5_default

**Comment by systemcrash** [comment] 2020-05-13 11:36
So, after performing a slightly more complex command of:

```
# docker-compose exec db psql -h localhost -U root
\c homer_data
You are now connected to database "homer_data" as user "root".
\dt
...
(367 rows)

select * from hep_proto_5_default;
...
....
 17526 | 662d7428-51a08047bcf-381e3f81 | 2020-05-13 09:04:33.350507+00 | {"dstIp": "2001:*************", "srcIp": "2001:***********", "dstPort": 58081, "srcPort": 61343, "protocol": 17, "captureId": "1", "payloadType": 5, "timeSeconds": 1589360673, "timeUseconds": 350507, "correlation_id": "662d7428-51a08047bcf-381e3f81", "protocolFamily": 10} | {"node": "1", "proto": "rtcp"} | {"report_count":1,"type":200,"ssrc":2824075690,"sender_information":{"ntp_timestamp_sec":20050,"ntp_timestamp_usec":657129472,"rtp_timestamp":1591042469,"packets":94802,"octets":15168320},"report_blocks":[{"source_ssrc":3033880513,"fraction_lost":0,"packets_lost":0,"highest_seq_no":116705,"ia_jitter":11,"lsr":916446682,"dlsr":1189831704}]}
(1209 rows)
```

I confirm that there are plenty of RTCP messages in the DB. What next?


I need to point out that I am also affected by the Homer bug #332 that I cannot specify a custom time-range.

**Comment by lmangani** [comment] 2020-05-13 11:39
Thanks - so great, now please try to select  a session with the Call-ID you're looking at and expecting results from. If there are results in the DB but not in the UI, we have a path for investigation to follow.

**Comment by systemcrash** [comment] 2020-05-13 11:52
I pull up the call, which shows up when searching by Correlation-ID, from the RTCP table column 2. I have results in the DB and in the UI. I click on the session-ID, to open the graph, and the QoS tab quickly disappears (probably as the script realises the tab is empty)

The request to http://myhost/api/v3/call/report/qos looks like

```json
{"param":{"id":{},"location":{},"search":{"1_call":{"callid":["662d7428-51a08047bcf-381e3f81@sipgt-696e2e71"],"id":36294,"uuid":[]}},"timezone":{"name":"Local","value":-120},"transaction":{"call":true,"registration":false,"rest":false}},"timestamp":{"from":1589320800000,"to":1589407199000}}
```

I notice the discrepancy between what the RTCP table has: `662d7428-51a08047bcf-381e3f81` and the QoS request has: `662d7428-51a08047bcf-381e3f81@sipgt-696e2e71` - important?

response
```json
{"rtcp":{"data":[],"total":0},"rtp":{"data":[],"total":0}}
```


What now? 

This graph is a mix of IPv4 and IPv6...

**Comment by systemcrash** [comment] 2020-05-13 12:10
> I notice the discrepancy between what the RTCP table has: `662d7428-51a08047bcf-381e3f81` and the QoS request has: `662d7428-51a08047bcf-381e3f81@sipgt-696e2e71` - important?
> 
> response

It turns out, boys and girls, that this is *very* important. I did a `copy -> cURL request` and modified the cURL request locally. When I removed the `@sipgt-696e2e71` portion, I got a shit-ton of results back. Kind of obvious now that I think about it.

**Comment by lmangani** [comment] 2020-05-13 12:16
Thanks for the details - they sure help and you're spot on - The correlation ID must match in order to return results. The real question is rather why the one you have in your RTCP reports is truncated. Could you perhaps confirm by locating any sessions without `@` or other special characters in the Call-ID returning RTCP statistics in the UI?

**Comment by lmangani** [comment] 2020-05-13 12:17
@systemcrash could you confirm what agent is pushing data into the setup?

**Comment by systemcrash** [comment] 2020-05-13 12:43
Our own agent. We largely followed the C and other source implementations of yours. 

So here's the thing - calls traverse the b2bua. As does media. The first leg might lack the `@blah` portion. The second leg (after traversal) will have it. 

I can search by the first shorter Call-ID (no `@blah` portion) and I only get that first call leg graphed, although no QoS. When I compare with the HEP3 packets, I am searching using the Correlation-ID which the RTCP packets had at HEP3 ingress. So it seems there should be a QoS tab for that. When I check in the DB, there are *definitely* RTCP entries for that Correlation-ID...

**Comment by systemcrash** [comment] 2020-05-13 12:50
Tried the cURL trick for that ID, but nothing comes back.

**Comment by lmangani** [comment] 2020-05-13 13:02
Those are literally two different sessions. In theory if the B2BUA correlation is configured right in Homer the backend should query both A and B leg call-ids for statistics, logs, etc. 

Are the calls correlated in the UI?

**Comment by systemcrash** [comment] 2020-05-13 13:08
> Those are literally two different sessions. In theory if the B2BUA correlation is configured right in Homer the backend should query both A and B leg call-ids for statistics, logs, etc.
> 
> Are the calls correlated in the UI?

Yes - the two legs show - but only if I search using the shorter ID via the correlation-ID field. It seems both calls correlate using the shorter ID only. 

Then if I click the longer (more specific) ID, I get both legs in the graph. If I click on the shorter, only the first leg in the graph. Neither show QoS. 

I guess that's what you mean by 'correlated'

**Comment by adubovikov** [comment] 2020-05-13 13:11
you can "fix" it using a correlation array in the UI settings. In this case you can write a simple javascript function that will cut-off the right part of callid after @ and add this as a new callid and the request will be for two callids: 662d7428-51a08047bcf-381e3f81@sipgt-696e2e71 and 662d7428-51a08047bcf-381e3f81

**Comment by systemcrash** [comment] 2020-05-13 13:13
> you can "fix" it using a correlation array in the UI settings. In this case you can write a simple javascript function that will cut-off the right part of callid after @ and add this as a new callid and the request will be for two callids: 662d7428-51a08047bcf-381e3f81@sipgt-696e2e71 and 662d7428-51a08047bcf-381e3f81

Thanks - this could be a workaround for the call I mentioned. But this last call I make, I get nothing back when I use the correlation-ID from the RTCP DB entries.

**Comment by adubovikov** [comment] 2020-05-13 13:13
![Screenshot from 2020-05-13 15-13-00](https://user-images.githubusercontent.com/4513061/81816921-465fbb00-952c-11ea-944f-8e75eab37141.png)

**Comment by adubovikov** [comment] 2020-05-13 13:14
> > you can "fix" it using a correlation array in the UI settings. In this case you can write a simple javascript function that will cut-off the right part of callid after @ and add this as a new callid and the request will be for two callids: 662d7428-51a08047bcf-381e3f81@sipgt-696e2e71 and 662d7428-51a08047bcf-381e3f81
> 
> Thanks - this could be a workaround for the call I mentioned. But this last call I make, I get nothing back when I use the correlation-ID from the RTCP DB entries.

check the query to PG and you will see why it doesnt' work

**Comment by systemcrash** [comment] 2020-05-13 13:15
Where can I monitor that?

**Comment by adubovikov** [comment] 2020-05-13 13:18
two ways:
1. activate debug in  the webapp
2. using ngrep on port 5432

**Comment by lmangani** [comment] 2020-05-13 13:18
@systemcrash for an unoptimized test, you can stick a '@%' postfix to the A-Leg to find the B-Leg.

**Comment by systemcrash** [comment] 2020-05-13 13:21
> @systemcrash for an unoptimized test, you can stick a '@%' postfix to the A-Leg to find the B-Leg.

When searching? No results when adding `@%` via the correlation-id search field

**Comment by systemcrash** [comment] 2020-05-13 13:22
> two ways:
> 
>     1. activate debug in  the webapp
> 

Where do I set this?

**Comment by adubovikov** [comment] 2020-05-13 13:24
> > two ways:
> > ```
> > 1. activate debug in  the webapp
> > ```
> 
> Where do I set this?

let me guess.... in the config file ? 

https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L65

**Comment by systemcrash** [comment] 2020-05-13 13:24
> > @systemcrash for an unoptimized test, you can stick a '@%' postfix to the A-Leg to find the B-Leg.
> 
> When searching? No results when adding `@%` via the correlation-id search field

OK - this works, but only via the Session ID and Call ID columns.

**Comment by adubovikov** [comment] 2020-05-13 13:25
@systemcrash you have already the solution - please make an own javascript function and it will solve YOUR issue

**Comment by systemcrash** [comment] 2020-05-13 13:30
> > > two ways:
> > > ```
> > > 1. activate debug in  the webapp
> > > ```
> > 
> > 
> > Where do I set this?
> 
> let me guess.... in the config file ?
> 
> https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L65

Oh, great. Well, as we mentioned in the other issue here yesterday https://github.com/sipcapture/homer-app/issues/340#issuecomment-626732633 this flag doesn't exist yet in the docker files. So when I try the debug flag, no go. :(

**Comment by systemcrash** [comment] 2020-05-13 13:32
> @systemcrash you have already the solution - please make an own javascript function and it will solve YOUR issue

Nope - overall functionality doesn't change. It's the same as listing search results. And the QoS tab still disappears.  :(

**Comment by adubovikov** [comment] 2020-05-13 13:32
this flag has nothing todo with DOCKER, this is a system param of homer-app, if you set it, you can see debug ouput

**Comment by adubovikov** [comment] 2020-05-13 13:34
> > @systemcrash you have already the solution - please make an own javascript function and it will solve YOUR issue
> 
> Nope - overall functionality doesn't change. It's the same as listing search results. And the QoS tab still disappears. :(

Let me make it short. You have two calls: call-ID: 123456 and 123456@aaa . You have only reports for "123456" and you wanna see reports once you click on "123456@aaa" ? Is it correct ?
If yes, you have to do manipulation in the correlation mapping to get real CALLID and send request for QOS for both.

**Comment by systemcrash** [comment] 2020-05-13 13:35
> this flag has nothing todo with DOCKER, this is a system param of homer-app, if you set it, you can see debug ouput

But where do I set it? I have to set that flag in the docker-compose.yml file so that homer picks it up. Doing this, there is no change in logging.

**Comment by systemcrash** [comment] 2020-05-13 13:37
> > this flag has nothing todo with DOCKER, this is a system param of homer-app, if you set it, you can see debug ouput
> 
> But where do I set it? I have to set that flag in the docker-compose.yml file so that homer picks it up. Doing this, there is no change in logging.

```
docker-compose exec homer-webapp bash
cat /usr/local/homer/etc/webapp_config.json
...
```

shows only

```
  "system_settings": {
    "hostname": "homer",
    "logname": "homer-app.log",
    "logpath": "/usr/local/homer",
    "uuid": "6c0033f0-9f89-40f3-a009-9369c7b271db"
  }
```

Those new lines which you recently added are not there...

**Comment by lmangani** [comment] 2020-05-13 13:49
I think the following correlation mapping block for call -> SIP should do the trick:
```
    {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i]+'@%'); }; returnData;"
    }
```

**Comment by systemcrash** [comment] 2020-05-13 13:55
> > > @systemcrash you have already the solution - please make an own javascript function and it will solve YOUR issue
> > 
> > 
> > Nope - overall functionality doesn't change. It's the same as listing search results. And the QoS tab still disappears. :(
> 
> Let me make it short. You have two calls: call-ID: 123456 and 123456@aaa . You have only reports for "123456" and you wanna see reports once you click on "123456@aaa" ? Is it correct ?
> If yes, you have to do manipulation in the correlation mapping to get real CALLID and send request for QOS for both.

Well, no - I have no QoS tab. 

I have reports for both legs. Stored under the truncated Correlation-ID in the RTCP table. 

I get good graphs for both IDs. I get both legs if I search using the truncated ID. I don't really care about the graphs. They're good. 

But no graph shows QoS tab.

**Comment by systemcrash** [comment] 2020-05-13 13:55
> I think the following correlation mapping block for call -> SIP should do the trick:
> 
> ```
>     {
>         "source_field": "data_header.callid",
>         "lookup_id": 1,
>         "lookup_profile": "call",
>         "lookup_field": "data_header->>'callid'",
>         "lookup_range": [
>             -300,
>             200
>         ],
>         "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i]+'@%'); }; returnData;"
>     }
> ```

Thank you - this is what I figured out from @adubovikov screenshot. Tried this, but still no QoS tab.

**Comment by lmangani** [comment] 2020-05-13 14:02
Ok - you need to see the QoS query and check it contains the modified callid too next.

**Comment by systemcrash** [comment] 2020-05-13 14:14
Ok - so searching for e.g. `662d7428-51a08047bcf-381e3f81` shows two calls

`662d7428-51a08047bcf-381e3f81@sipgt-696e2e71`
and
`662d7428-51a08047bcf-381e3f81@sipgt-08f97125`

I can only graph one by clicking on it. 

I dig into the query stuff, and I see the QoS query contains the `@sipgt-696e2e71` portion. How do I truncate this? Mappings? HepSub?

**Comment by adubovikov** [comment] 2020-05-13 14:17
no the question: why you have "@sipgt-696e2e71" in the QOS query. Is it
callid ?

**Comment by systemcrash** [comment] 2020-05-13 14:20
It seems to. I click on the search result to graph that call-ID (result column Session-ID).

**Comment by systemcrash** [comment] 2020-05-13 14:25
OK - after your script suggestion, I *finally* get a QoS tab for a call, but ONLY IF THE CALL ID, SESSION ID, and CORRELATION ID I clicked on CONTAINS NO `@portion`

**Comment by systemcrash** [comment] 2020-05-13 14:26
So ANY call ID which contains an `@portion`, does not get a QoS graph.

**Comment by adubovikov** [comment] 2020-05-13 14:29
fix your function: pseudo code:
```
var position = callid.has("@");
if(positon != -1) { 
             returnData.push(callid.substr(0,position)); 
}
```

**Comment by systemcrash** [comment] 2020-05-13 14:40
We ingest Calls from many endpoints, and they will often already contain an `@portion`, so being able to handle this in general seems important. 

https://tools.ietf.org/html/rfc3261#section-8.1.1.4
```
8.1.1.4 Call-ID

   The Call-ID header field acts as a unique identifier to group
   together a series of messages.  It MUST be the same for all requests
   and responses sent by either UA in a dialog.  It SHOULD be the same
   in each registration from a UA.
...

   Use of cryptographically random identifiers (RFC 1750 [12]) in the
   generation of Call-IDs is RECOMMENDED.  Implementations MAY use the
   form "localid@host".  Call-IDs are case-sensitive and are simply
   compared byte-by-byte.

      Using cryptographically random identifiers provides some
      protection against session hijacking and reduces the likelihood of
      unintentional Call-ID collisions.

   No provisioning or human interface is required for the selection of
   the Call-ID header field value for a request.

   For further information on the Call-ID header field, see Section
   20.8.

   Example:

      Call-ID: f81d4fae-7dec-11d0-a765-00a0c91e6bf6@foo.bar.com
```

**Comment by systemcrash** [comment] 2020-05-13 14:53
Let me ask this another way: should correlation-IDs be truncated when they go into the RTCP table? Or should they contain the full call-ID?

**Comment by systemcrash** [comment] 2020-05-13 14:54
> fix your function: pseudo code:
> 
> ```
> var position = callid.has("@");
> if(positon != -1) { 
>              returnData.push(callid.substr(0,position)); 
> }
> ```

This should go in the same mapping->SIP->call?

**Comment by lmangani** [comment] 2020-05-13 16:03
Perhaps you should just reverse the logic and truncate the suffix?

```
{
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
    }
```

**Comment by systemcrash** [comment] 2020-05-13 16:09
> Perhaps you should just reverse the logic and truncate the suffix?
> 
> ```
> {
>         "source_field": "data_header.callid",
>         "lookup_id": 1,
>         "lookup_profile": "call",
>         "lookup_field": "data_header->>'callid'",
>         "lookup_range": [
>             -300,
>             200
>         ],
>         "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
>     }
> ```

Thank you. This gives all call legs in the one flow now. ( Altho the QoS tab still disappears - QoS tab only appears if I click on a call-ID which doesn't end with `@fqdn`)

**Comment by lmangani** [comment] 2020-05-13 16:15
Great. Next check what the QOS query receives as parameters and we can figure that one out too.

**Comment by systemcrash** [comment] 2020-05-13 16:20
No - just the full:

```json
{"param":{"id":{},"location":{},"search":{"1_call":{"callid":["102649ZDVhYjMxODdjYjI3MWJjNzRhMTM3ODU1NmI4NGYwMDU@sipgt-08f97125"],"id":36874,"uuid":[]}},"timezone":{"name":"Local","value":-120},"transaction":{"call":true,"registration":false,"rest":false}},"timestamp":{"from":1589320800000,"to":1589407199000}}
```

If I click on any result with Call/Session-ID contains `@fqdn` then that portion is appended to the QoS query.

**Comment by lmangani** [comment] 2020-05-13 17:02
You need to perform the correlation for HEP type 5 (RTCP) to complete the mix:
```
{
        "source_field": "data_header.callid",
        "lookup_id": 5,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
    }
```

**Comment by systemcrash** [comment] 2020-05-13 17:58
> You need to perform the correlation for HEP type 5 (RTCP) to complete the mix:
> 
> ```
> {
>         "source_field": "data_header.callid",
>         "lookup_id": 5,
>         "lookup_profile": "default",
>         "lookup_field": "sid'",
>         "lookup_range": [
>             -300,
>             200
>         ],
>         "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
>     }
> ```

And this also goes under the same mapping->call->SIP?

My correlation now looks like:
```json
[
    {
        "source_field": "data_header.callid",
        "lookup_id": 100,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.callid",
        "lookup_id": 5,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
    },
    {
        "source_field": "protocol_header.correlation_id",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
    }
]
```

But still no QoS tab - and qos query seems to only contain the `@fqdn` part. Should there be multiple entries there?

**Comment by bibace** [comment] 2020-05-14 11:26
I have a similar issue, I can see QoS tab, but it shows Corrupted data packet came from server.

main.436c274b9439f9e24d8a.js:1 Error: SyntaxError: Unexpected token I in JSON at position 0
    at e.onErrorMessage (main.436c274b9439f9e24d8a.js:1)
    at main.436c274b9439f9e24d8a.js:1
    at Array.forEach (<anonymous>)
    at e.parseRTP (main.436c274b9439f9e24d8a.js:1)
    at e.ngOnInit (main.436c274b9439f9e24d8a.js:1)
    at tt (main.436c274b9439f9e24d8a.js:1)
    at main.436c274b9439f9e24d8a.js:1
    at et (main.436c274b9439f9e24d8a.js:1)
    at Ze (main.436c274b9439f9e24d8a.js:1)
    at _o (main.436c274b9439f9e24d8a.js:1)

**Comment by lmangani** [comment] 2020-05-14 11:59
@bibace same as above, please try the new version and attach the debug output of hepfix to get help

**Comment by lmangani** [comment] 2020-05-14 12:00
@bibace please open a separate issue if its about the data not the correlation - thanks!

**Comment by lmangani** [comment] 2020-05-14 12:01
| qos query seems to only contain the @fqdn part. Should there be multiple entries there?
@adubovikov could you comment if the above correlation mapping should work?

**Comment by lmangani** [comment] 2020-05-14 12:03
@systemcrash I think your settings are wrong, check my example uses lookup profile `default` could be worth checking ad-verbatim

**Comment by adubovikov** [comment] 2020-05-14 12:05
@systemcrash        

``` 
"lookup_profile": "call",
```
should be changed to "default", because the RTCP table has format: hep_proto_5_default 

anyway, if it will not work, please provide us the SIP and RTCP dump and we can reproduce the issue in the our lab.

**Comment by systemcrash** [comment] 2020-05-14 12:09
> @systemcrash
> 
> ```
> "lookup_profile": "call",
> ```
> 
> should be changed to "default", because the RTCP table has format: hep_proto_5_default
> 
> anyway, if it will not work, please provide us the SIP and RTCP dump and we can reproduce the issue in the our lab.

Can't see why this should have an effect - QoS tab appears fine for other calls. If I make the change to default, like so:
```json
    {
        "source_field": "data_header.callid",
        "lookup_id": 5,
        "lookup_profile": "default",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
    },
```
then Homer graphs the RTCP packets as if they were SIP.  But at least it graphs them for call-ids with `@fqdn`

**Comment by systemcrash** [comment] 2020-05-14 12:15
> You need to perform the correlation for HEP type 5 (RTCP) to complete the mix:
> 
> ```
> {
>         "source_field": "data_header.callid",
>         "lookup_id": 5,
>         "lookup_profile": "default",
>         "lookup_field": "sid'",
>         "lookup_range": [
>             -300,
>             200
>         ],
>         "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i].split('@')[0] ); }; returnData;"
>     }
> ```

Seeing as my earlier question went unanswered: please state exactly where this should go?

> this also goes under the same mapping->call->SIP?

**Comment by systemcrash** [comment] 2020-05-14 12:17
Side question: is there a factory reset, where I don't nuke all data? ( So I can get back to some known sane settings combination )

**Comment by lmangani** [comment] 2020-05-14 12:21
@systemcrash 

- `yes` it goes in the SIP -> Call correlation (source of event) so I took that for granted - unless you want to do this for other types as well, that's up to you 

- `no` selective factory reset only mass factory reset through homer-app provisioning so keep your config backups handy.

**Comment by systemcrash** [comment] 2020-05-14 12:26
OK - thank you. No - doing that change just graphs the RTCP packets along with the SIP. Fun but... not quite what we are aiming for. 🗡️

**Comment by lmangani** [comment] 2020-05-14 12:28
No idea what you're aiming for :) If this is a platform integration, perhaps you should email support@qxip.net to arrange a consultancy

**Comment by systemcrash** [comment] 2020-05-14 12:32
> No idea what you're aiming for :) If this is a platform integration, perhaps you should email [support@sipcapture.org](mailto:support@sipcapture.org) to arrange a consultancy

out of the box functionality :)

I'll nuke the config and start from the bottom up. 

But one helpful question which I asked three times here: Should correlationID contain `@fqdn` portion, or should that always be truncated at capture? ( as opposed to ingress to heplify )

**Comment by lmangani** [comment] 2020-05-14 12:48
Out of the box functionality with a custom correlation logic? That's called magic ;)

Jokes aside, as you see we're happy to take user feedback and account for gaps of course. The lookup you're describing works on my side (that's why I suggested it) but evidently there's something else at play or some patches in my version unpushed. We'll further check.

**Comment by systemcrash** [comment] 2020-05-14 14:42
No - I nuked everything - the DB from the ground up.  Same result. 


Here is my understanding, please correct me if I got something wrong. 

* Call leg A and Call leg B which are two parts of the same call, and each may have a different Call-ID, (should) get the same CorrelationID. 

* At HEP capture, Call leg A and Call leg B and their RTCP get assigned a solitary, and unique CorrelationID. 

* Searching for calls against the CorrelationID will pull up Call leg A and Call leg B 

* Graphing one, the other or both of Call leg A and Call leg B will produce a QoS for Call leg A and Call leg B 

Or did I get this wrong, and every call leg should have its own CorrelationID?

**Comment by lmangani** [comment] 2020-05-14 14:54
Hey @systemcrash your assumptions are more or less correct, but note:

> Call leg A and Call leg B which are two parts of the same call, and each may have a different Call-ID, (should) get the same CorrelationID.

Not necessarily - the capture ID for sessions can be filled by the agent if there's a known B2BUA element for SIP type or remain empty. It's instead 100% required to type 100/5/34/etc in order to be found in relation to sessions, or session groups in this case.

> At HEP capture, Call leg A and Call leg B and their RTCP get assigned a solitary, and unique CorrelationID.

RTCP gets assigned the Call-ID of the SIP session with the matching SDP. Not solitary or unique but rather of an associative nature (if correctly detected, that is)

> Searching for calls against the CorrelationID will pull up Call leg A and Call leg B

Not really, but clicking either A or B should return both legs and their connected data. 

> Graphing one, the other or both of Call leg A and Call leg B will produce a QoS for Call leg A and Call leg B

This should be the case and I think the last element is the failing one to investigate.

**Comment by systemcrash** [comment] 2020-05-14 15:21
> > At HEP capture, Call leg A and Call leg B and their RTCP get assigned a solitary, and unique CorrelationID.
> 
> RTCP gets assigned the Call-ID of the SIP session with the matching SDP. Not solitary or unique but rather of an associative nature (if correctly detected, that is)
> 

So Call leg A and Call leg B get same CorrelationID. 

RTCP for each leg should get its leg CorrelationID = its leg CallID?

**Comment by lmangani** [comment] 2020-05-14 15:31
@systemcrash No that's a wrong assumption, although possible, the correlation_id header is a commodity but not a requirement. This is what the mapping scripts are really for, resolving other legs regardless of them having a correlation_id or just a Call-ID based on any custom logic. You can go from A to B using a Call-ID match, from B to C using other logic, and so on for both SIP and other HEP types.

The RTCP reports will get a correlation_id equal to the SIP Session the agents associates them with.

**Comment by systemcrash** [comment] 2020-05-14 15:45
> @systemcrash No that's a wrong assumption, although possible, the correlation_id header is a commodity but not a requirement. This is what the mapping scripts are really for, resolving other legs regardless of them having a correlation_id or just a Call-ID based on any custom logic. You can go from A to B using a Call-ID match, from B to C using other logic, and so on for both SIP and other HEP types.
> 

OK - this much is what we can do with 'magic' later on. But to avoid having to do magic:

> The RTCP reports will get a correlation_id equal to the SIP Session the agents associates them with.

We should probably assign Leg B RTCP correlation_id = Leg B call-ID so that when it goes into the DB, it is stored correctly. And not assign Leg B RTCP correlation_id = Leg A RTCP call-ID

Seems reasonable?

**Comment by systemcrash** [comment] 2020-05-31 20:09
Hi @lmangani - if you could confirm something, this would be instrumental in fixing some behaviour we have. Just a yes or no will suffice.

You wrote:
>  RTCP gets assigned the Call-ID of the SIP session with the matching SDP. 

So, based on the heplify code, e.g.:

https://github.com/sipcapture/heplify/blob/9bd83e8761c96166d55d09d05ce0ef42d94e41a3/decoder/correlator.go#L257

The way things should operate is that, RTCP/JSON in a call must get the SIP Call-ID (i.e. the HEP packet corrid field is filled with the SIP callid). 

(you're basically confirming that this is what the above-mentioned code in `heplify` does: step 1 - cache the SIP call-id for an SDP which 'owns' an RTCP stream. Step 2 - got an RTCP packet? Search cache and give it the call-id, and fill corrid with RTCP call-id)

**Comment by lmangani** [comment] 2020-06-01 08:19
@systemcrash I don't understand the confusion here. I suppose the answer is `yes`

**Comment by systemcrash** [comment] 2020-06-11 13:33
@lmangani @adubovikov  - thank you for your help in this long-running thread!

There are some good examples here to help understand how the mappings work. 

We located the problem - the Call-ID in for egress HEP  RTCP packets was (being) truncated after the `@` - unfortunately none of the recommendations in this thread were able to restore the QoS tab with data formatted so. The QoS tab operates independently of mappings (seems to, anyway) and does not work to re-connect with SIP calls where its Call-ID has the `@...` portion. 

The above proposals worked to display RTCP packets inline in the call graphs (with signalling). 

A battle for another day :)

**Closed** 2020-06-11 13:34 UTC
