### ISSUE TITLE
table sort in descending time order sorts by time of first register

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#126] opened 2019-04-14 19:02 UTC
I look at the search results for registrations and I see the first REGISTER messages in the results.

I click to sort in descending time order.

It continues to show old entries, not recent REGISTER messages, although they are sorted in descending order for the time of the first REGISTER message from each client.

This is a little bit confusing.

**Comment by lmangani** [comment] 2019-04-14 19:28
What happens when you click the sorting multiple times?

**Comment by lmangani** [comment] 2019-11-28 19:11
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!

**Closed by lmangani** 2019-11-28 19:11 UTC

**Comment by yeyo** [comment] 2020-04-28 09:10
I think the problem is query from "statistic.go". Could you please update line 
`infQuery = fmt.Sprintf("SELECT %s FROM %s.%s.\"%s\" WHERE time > %d AND %d > time %s GROUP BY time(%s) FILL(null) LIMIT %d;"`
with
`infQuery = fmt.Sprintf("SELECT %s FROM %s.%s.\"%s\" WHERE time > %d AND %d > time %s GROUP BY time(%s) FILL(null) order by time DESC LIMIT %d;"`
and test again?

**Comment by adubovikov** [comment] 2020-04-28 09:45
done
