### ISSUE TITLE
Homer UI - Pop-Up window issues

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer-app#517] opened 2023-05-04 10:05 UTC
hey, 

when i click on the pup up windows button from the thumbnail of the session. i see 2 issues.

1. The pop up try to load the "flow" tab but shows nothing besides "All item were filtered, check filter settings" - 
this solves when i click on a different tab like "message" or "session info" and click back to the flow which successfully load.

2. the url of the pop up is composed of : https://homer-ip/transaction/"session-id" -
when i open the url on a different tab or window on the browser its loads infinitely 

this what shows in the web console:

![image](https://user-images.githubusercontent.com/130898221/236174326-cc169fef-5b41-456a-bebd-7106a9ea7ef1.png)

**Comment by idanam-del** [comment] 2023-05-08 10:02
bump

**Comment by lmangani** [comment] 2023-05-08 10:25
I could not reproduce this issue on our deployments. 
Please provide more information about your deployment or how to reproduce it on a fresh setup.

**Comment by idanam-del** [comment] 2023-05-08 10:40
the deployment we use is as referred in this:
![image](https://user-images.githubusercontent.com/130898221/236803539-6374d998-1a78-4509-9568-9c186a3ac32c.png)
On deb 11 VM

**Comment by idanam-del** [comment] 2023-05-08 12:56
> Referring to our own installation guides will not help much. Please describe how to reproduce your issue step by step.

You've asked me more information about the deployment, ive referred that the deployment is the one from the installation guide.

To reproduce the steps you need to do the following(shown from a "hom7-prom-all" docker deployment):

1. open up a sip message window from the widget:
![image](https://user-images.githubusercontent.com/130898221/236828889-4b72c933-078f-4449-852a-161f5e84cccd.png)
2. click on the "pop up" button:(circled in red)
![image](https://user-images.githubusercontent.com/130898221/236829102-2c1f2d4d-7674-437f-92b1-1dff7e271614.png)
3.Copy the url provided in the pop up window
4.paste and go to the url on a different browser 
5.login at the prompt
6.At this step you can see its loads indefinably with the provided errors at the start of the thread in the web console.

**Comment by AlexeyOplachko** [comment] 2023-05-08 14:26
So for 2) this is not a bug, this is just unsupported behavior. Pop up window gets data directly from the window you've opened before, and you can not just copy it somewhere else.

For the first issue, while I wasn't able to replicate it, I implemented some fixes that might resolve it, I'll make a PR later today, and write in here, please give us update if it still happens for you.

**Comment by idanam-del** [comment] 2023-05-09 07:39
> So for 2) this is not a bug, this is just unsupported behavior. Pop up window gets data directly from the window you've opened before, and you can not just copy it somewhere else.
> 
> For the first issue, while I wasn't able to replicate it, I implemented some fixes that might resolve it, I'll make a PR later today, and write in here, please give us update if it still happens for you.

I see, thank you.

I guess the closest feature to it is the homer-view. too bad its not working for me right now...

**Comment by kYroL01** [comment] 2023-12-21 09:26
The issue is fixed in the last Homer version.
Please re-open it if it's not resolved on your side.

**Closed by kYroL01** 2023-12-21 09:26 UTC
Labels: stargazed

**Comment by naqashsaeed** [comment] 2023-12-21 10:35
@kYroL01 yes i have also tested it on my side, and for me it is working fine.
it only takes 1 or 2 seconds to load and then flow tab is appear.
